### PR TITLE
Added Support to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by fossfreedom** [comment]
hmm....

  I think a wget of the package would suffice here + a sudo apt install ./packagenameversion.deb - we shouldn't try to mix/match debian and ubuntu repos.

Even a wget of a debian package is a bad idea - but hey-ho - until the project is reworked to remove the obsolete webkit bits, wget is best we can do here.

**Comment by ghost** [comment]
Hello

got it. it is dangerous to make this mixture of servers. But I tested it and it worked fine without too many problems. But I will try to do some tests here using ubuntu's own servers ,.

image

**Comment by ghost** [comment]
I just saw here that until 18.04 (bionic), gir1.2-webkit3.0 existed. https://packages.ubuntu.com/search?keywords=gir1.2-webkit-3.0

I will do a test with this server to see if it works.

**Comment by ghost** [comment]
it worked perfectly with Ubuntu's Universe server. I remade the patch.

**Comment by ghost** [comment]
about Wget, gir1.2-webkit-3.0 needs several dependencies (at least about 6), I already did that and it is very annoying because one dependency pulls the other. I found it easier to add the repository to sources.list and after installed, delete the line.

**Pull request merged**
